services:
  backend:
    build:
      context: ./backend
    container_name: tunelog-backend
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: tunelog-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend